### ISSUE TITLE
Test for road network in Leeds

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#101]

**Comment by anisotropi4** [comment]
@Robinlovelace I'm not sure what to do here as I can't find the code nor data in the repository.  I've just `git pull` and it doesn't seem to be there in the repository `networkmerge`. I also don't seem to be able to find `coherentnet`.

**Comment by Robinlovelace** [comment]
Can you add it to this script? https://github.com/nptscot/networkmerge/blob/main/tests/leeds.qmd

Ideal would be to re-write the code to import a module to avoid defining the functions and simply use the updated version of the module, starting with

```python
import networkmerge
```

but happy with whatever works.

**Comment by Robinlovelace** [comment]
Ideally as a PR rather than pushing to main but again that's optional.
