### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#108]
With the following message:

```
  ✖ Failed to build rsgeo 0.1.6.9000
```

Any ideas @JosiahParry ?

**Comment by JosiahParry** [comment]
Theres nothing in the CI that indicates why it may be failing. There's no compilation log. It looks like the installation was stopped before it even began?
<img width="682" alt="image" src="https://github.com/nptscot/networkmerge/assets/13534508/b4462081-fa2a-4cea-abe2-8a36bd002e41">

**Comment by Robinlovelace** [comment]
Maybe...
