### ISSUE TITLE
Mention sgeop

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#119]
Well worth mentioning, have seen the results and they are good: https://github.com/uscuni/sgeop

Discussed today with @martinfleis. As I said, would welcome contributions + coauthorship in the paper, good to have comparator implementations.

**Comment by martinfleis** [comment]
Hey, just to provide some context.

This still very much WIP but there's a working prototype algo now that uses the detection of artifacts based on https://josis.org/index.php/josis/article/view/319 and uses that to detect which parts of the network need to be simplified. 

The algorithm itself deals independently with artifacts forming a single polygon, where it attempts to preserve existing continuity of the network (as captured by [COINS](http://docs.momepy.org/en/stable/user_guide/graph/coins.html) algo) and artifacts that are forming larger clusters, where we use Voronoi-based solution but attempt to preserve planarity where possible.

When using it, you will notice that it occasionally simplifies stuff where it should not (typically small, weirdly-shaped blocks). For that we have `exclusion_mask` that can contain for example building layer from OSM and ensures that any polygon intersecting any geometry in exclusion_mask is not simplified.

Done in collab with @anastassiavybornova and @jgaboardi!
