### ISSUE TITLE
Final tweaks to methods

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#120]
- [x] Clarify methods in Section 3.2.1

Currently the section contains 3 figures, each with buffers. Could these be compressed into a couple or a single figure? Also it's not totally clear how we go from the buffered representation to truncated and segmented and then segmented buffer geometries in what are currently figures 6 and 7, as shown below: 

https://nptscot.github.io/networkmerge/paper.html#create-a-projected-combined-buffered-geometry

- [x] I suggest we remove section 3.2.3 on affine transformations, unless we can explain how and when the different types of affine transformations are used.

- [x] Updating the section `3.2.4 Skeletonize the buffer to a point geometry`, is this the correct subheading title? Overall I think the whole of 3.2 could be written more clearly, what do you think about removing the subheadings @anisotropi4 ?

- [x] I think that the Voronoi approach is really well written, but could benefit from removing subheadings also, possibly.

I think that's pretty much it.

**Comment by anisotropi4** [comment]
Close as changes have been merged.

**Comment by anisotropi4** [comment]
Changes have been merged.
