### ISSUE TITLE
Try polygon -> centreline approach

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#22]
Hi @wangzhao0217 I found this and wondered if this could help? https://github.com/fitodic/centerline

That raises the question of how to create a polygon of each corridor. Union and then buffer operation on projected data e.g. with 10 or 20 m or x m buffer, could work well. 

More blueskies idea: use imagery data to generate polygons.

**Comment by wangzhao0217** [comment]
Hi Robin, do you remember this is the same as my first attempt to find the centreline for two parallel lines?  Would utilizing imagery data to create polygons be very computationally intensive?

**Comment by Robinlovelace** [comment]
> Hi @Robinlovelace , do you remember this is the same as my first attempt to find the centreline for two parallel lines? Would utilizing imagery data to create polygons be very computationally intensive?

Yes I recall that.

I think using imagery data would be intensive but not sure if that would prevent it from being used in our case for network data covering all of Scotland. What do you think?

An alternative would be to union and then create buffers around possibly parallel lines, e.g. based on name and Hausdorf distance, worth trying that also?

**Comment by wangzhao0217** [comment]
> > Hi @Robinlovelace , do you remember this is the same as my first attempt to find the centreline for two parallel lines? Would utilizing imagery data to create polygons be very computationally intensive?
> 
> Yes I recall that.
> 
> I think using imagery data would be intensive but not sure if that would prevent it from being used in our case for network data covering all of Scotland. What do you think?
> 
> An alternative would be to union and then create buffers around possibly parallel lines, e.g. based on name and some measure of distance e.g. Hausdorff or Frechet https://en.wikipedia.org/wiki/Fr%C3%A9chet_distance worth trying that also?

got it thanks Robin, I will think about it

**Comment by anisotropi4** [comment]
Having tried Hausdorff and Frechet with combining networks, there is some tuning required around segment length. My experience was Hausdorf is quite limited unless you break up the line into short chunk, while Frechet is quite computationally intensive. YMMV

**Comment by Robinlovelace** [comment]
YMMV?

**Comment by anisotropi4** [comment]
"Your Mileage May Vary". Apparently it was a caveat in advert on the sale of car-tyres in the US. As in "5,000 miles of trouble free driving...your mileage may vary"

**Comment by Robinlovelace** [comment]
Aha. Old school reference there, makes sense (just about)!
