### ISSUE TITLE
Logical networks, accuracy, meta-data and, python modules (OSMNX, networkx and Shapely)

### ISSUE THREAD

**Issue by anisotropi4** [nptscot/networkmerge#25]
Having read the paper and slept on this I think there are a number of areas I'd want to consider:
1.  A logical transport network: a model to help communication and decision making rather than a geographically accurate map Examples, would be the classic TfL tube map, or the bus route maps in Sheffield. Very heavily used in rail and for things like planning and operations systems.
2. Trivial simplification: There is a trivial simplification based on a projected geography where you simply round coordinates to an arbitrary value say, 1m. This effectively imposes a network grid on the data and implicitly simplifies the network. You may want to extend this to, say 5m, or use a difference base tiling geometry and build a network based on centre-points.
3. Meta-data simplification: Rather than simply aggregate a network based on proximity, you may also want rules based on other characteristics such as road classification. For example, there may be valid rules based on simplifying parallel cycle and pedestrian infrastructure with roads where it is legal, for example, a city road grid, but not where it is illegal. For example, where a segregated path runs along side a motorway. Where it is illegal to cycle or walk.
4. OSMX, networkx and Shapely: These comes with a whole set of things for simplifying and manipulating networks. It might be worth having a review of what is out there.

Arguably these are actually four "issues" and would take advice on how to manage these. I'm in the process of setting up my Quarto environment with the relevant emacs inferior-mode.

(With regards point 2, I would love to see what aperiodic tiling might do here, but perhaps should get out more)

**Comment by Robinlovelace** [comment]
Many thanks for your thoughts Will! Following a review, and some chat with people 1-2-1 and on social media ([Twitter](https://twitter.com/robinlovelace/status/1687399438170370048) and [Mastodon](https://fosstodon.org/@robinlovelace/110830706363249530)) I agree with your areas. Converting those into sections of a paper I'm thinking

- Introduction: there is a need for simpler and easier to read network maps for various policy purposes, the one outlined in the draft paper being just one. I think we can talk about levels of simplification, with 'tube maps' being one extreme', in the intro, covering you "1."
- Methods: there are many methods to choose from and seemingly no paper has yet systematically compared open options. This is somewhere this paper/project/codebase can add a lot of value I think. I think "rounding coordinates" and other things in your "2." and "3." can fit nicely into this pre-existing section, right? Maybe we should have a separate section, possibly after methods, on implementations, where we can actually demonstrate some of these packages, including `osmnx`, GRASS, other approaches, so should we add an 'implemenations' section after this one?  https://github.com/nptscot/networkmerge/blob/main/paper.md#methods

Good luck reproducing where we've got to, Quarto is a great system, let me know how you get on and happy to do a quick video call at some point to get you up-to-speed.

**Comment by Robinlovelace** [comment]
Closing for now, anything from this that can go into the paper let us know @anisotropi4
