### ISSUE TITLE
'Bunching' of network results after consolidating intersections

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#27]
As shown below the function seems to create some interesting bunching, with many lines going to a few selected nodes.

![image](https://github.com/nptscot/networkmerge/assets/1825120/c7dffd96-0eba-43e3-a7b7-4cf3c10f8537)

**Comment by Robinlovelace** [comment]
OK actually yes this is pretty cool: the bunching is useful, should be easy to merge the new parallels that all go to these consolidated junctions right @martinfleis ? 
![image](https://github.com/nptscot/networkmerge/assets/1825120/bc10fd73-8eff-49fd-840f-4bf6d5fef2da)

**Comment by martinfleis** [comment]
You get closer with this, yes. In the ideal case, two parallel lines should now start from the same node and and in the same node. You could match them based on that, filter out edge cases (there are situations when you don't want to merge) and get some form of an average line. It gets trickier when they do share a node on one and but not the other and when there are more than 2 parallel lines.

**Comment by Robinlovelace** [comment]
Sounds good, that was my thinking, many thanks for ideas bouncing on this! Functions that eventually package this should have a way to specify which aggregating function to apply to each variable, e.g.

```python
nm.netmerge(net, tol = 10, ..., aggregations=['bike=sum(bike)', 'car=sum(car)', 'gradient=mean(gradient)'])
```

If that makes any sense?

**Comment by martinfleis** [comment]
Yes, a way of specification how to aggregate data would be nice. I would suggest to mimic pandas groupby API and pass a dict but that is just a minor detail. It is also a question what should happen with edges that collapse to a node.

So far, I was interested only in geometries :).
