### ISSUE TITLE
Use identical inputs in example plots

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#30]
Currently we have at least 3 different input datasets shown:

![image](https://github.com/nptscot/networkmerge/assets/1825120/c966135e-3011-4c6a-b66f-63bf361eb09a)

![image](https://github.com/nptscot/networkmerge/assets/1825120/e29e4a24-bdd5-4d9e-8202-d67ed9225e43)
 
Which is I think useful to show standard simplification

And 2 versions of the central Edinburgh route network:

![image](https://github.com/nptscot/networkmerge/assets/1825120/fa64daec-b54d-4ca5-8a43-715e76e70ee4)

We should consolidate. @anisotropi4 I'm thinking that if we go with the first, that has clearly described issues, that could be good, I can pull down data from Otley Road and Armley Road, shown, if that would help with this.

**Comment by Robinlovelace** [comment]
Sound reasonable?

**Comment by anisotropi4** [comment]
This is fine @Robinlovelace. Just let me know which `GeoJSON` file I need to load as I just need to change to whatever the path to the Leeds file is. The current code loads the data into a `base_nx` dataframe on line 317

```{python}
base_nx = gp.read_file("data/rnet_princes_street.geojson").to_crs(CRS)
 ```

**Comment by Robinlovelace** [comment]
OK, and I should be able to do that in the code with a simple search and replace. We can try different input datasets to see which work best for different things and there's a balance between the benefits of using few datasets (consistency, readability) vs using many (showing how each approach performs in a range of circumstances).
