### ISSUE TITLE
Error sf::read_sf

### ISSUE THREAD

**Issue by anisotropi4** [nptscot/networkmerge#31]
When running through the code I get to about line 116:

    gdf = sf::read_sf("data/rnet_princes_street.geojson")
            ^
    SyntaxError: invalid syntax

Although likely an environment issue on my side, I can't then see where the following code is defined:

    gdf = sf::read_sf("data/rnet_princes_street.geojson")
    gdf_road = sf::read_sf("data/edges.shp")
    library(tmap)
    tmap_mode("view")
    m = tm_shape(gdf_road) +
    tm_lines("blue", lwd = 9) +
    tm_shape(gdf) +
    tm_lines("red", lwd = 3) 
    dir.create("maps")
    tmap_save(m, "maps/edinburgh.html")
    browseURL("maps/edinburgh.html")

Thoughts or comments welcome

**Comment by Robinlovelace** [comment]
It's defined here:

https://github.com/nptscot/networkmerge/blob/30248e60f756317a3507378c6090a4fd6e43c804/README.qmd#L131-L143

I'm not 100% sure what's going on, can you provide more info on what you tried?

It's reproducible for sure, but you need a working and R installation (that is R code not Python, could that explain it?).

**Comment by Robinlovelace** [comment]
Any luck with this @anisotropi4 ?

**Comment by anisotropi4** [comment]
Yup. I need to install R and work with that. As noted, it is an environment issue.

**Comment by Robinlovelace** [comment]
Awesome. Looking forward to testing some of your ideas + code on our example datasets + use cases.
