### ISSUE TITLE
Port content from stplanr vignette into merge.qmd

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#53]
I put my working on using the new `rnet_merge()` function here: https://github.com/ropensci/stplanr/blob/master/vignettes/merging-route-networks.Rmd

The updated functions, simple description, and resulting maps should go into `merge.qmd` :pray:

**Comment by wangzhao0217** [comment]
@Robinlovelace Hi Robin, I have taken updated functions, simple description, and resulting maps from merging-route-networks.Rmd into merge.qmd. you may close it after review

**Comment by Robinlovelace** [comment]
Hi Zhao, can you point me to the PR?

**Comment by wangzhao0217** [comment]
Hi Robin,
I directly edited merge.qmd with commit in main
as merging-route-networks.Rmd in another repo.
However, I now realise that the correct approach would have been to create
a new branch, make the necessary edits there, and then submit a pull
request (PR) to merge the changes.
To rectify this, I will reverse my previous change, create a new branch,
make the edits, and send you PR.
I am very sorry and I will be careful.
Best regards,
Zhao

**Comment by Robinlovelace** [comment]
No problem Zhao and thanks for the update. Will take a look tomorrow and review your code, probably tomorrow afternoon.
