### ISSUE TITLE
Issue in `paper.qmd`: Unexpected token '.' in `purrr::map_dfr(...)`

### ISSUE THREAD

**Issue by anisotropi4** [nptscot/networkmerge#60]
Running `quarto` on `paper.qmd` the two calls to `purr::map_df` fail with:

    Error in `map()`:
    ℹ In index: 1.
    Caused by error:
    ! SyntaxError: Unexpected token '.'
    Backtrace:
      1. purrr::map_dfr(...)
      17. base::stop(`<std::nv_>`)
    Execution halted
 
I think this corresponds to:

    input_simplified = purrr::map_dfr(simplification_levels, .id = "id", function(x) {  
       rmapshaper::ms_simplify(input_projected, keep_shapes = TRUE, keep = x)
    })

**Comment by Robinlovelace** [comment]
Thanks for the report @anisotropi4, I cannot reproduce the behaviour. Here's a minimal example:

``` r
library(sf)
#> Linking to GEOS 3.11.1, GDAL 3.6.4, PROJ 9.1.1; sf_use_s2() is TRUE
library(tidyverse)
library(rmapshaper)
#> The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
#> which was just loaded, were retired in October 2023.
#> Please refer to R-spatial evolution reports for details, especially
#> https://r-spatial.org/r/2023/05/15/evolution4.html.
#> It may be desirable to make the sf package available;
#> package maintainers should consider adding sf to Suggests:.
library(tmap)
#> 
#> Attaching package: 'tmap'
#> The following object is masked from 'package:datasets':
#> 
#>     rivers
input = sf::read_sf('https://github.com/nptscot/networkmerge/raw/main/data/minimal-input.geojson')
input_projected = sf::st_transform(input, "EPSG:27700")
simplification_levels = c(1, 0.5, 0.1, 0.001)
# ordered factor of simplification levels:
simp_factor = ordered(simplification_levels, levels = simplification_levels)
simplification_df = data.frame(
  id = as.character(1:length(simplification_levels)),
  simp_factor,
  keep = paste0("Keep: ", round(as.numeric(simplification_levels) * 100, 2), "%")
  )
simplification_df$keep = ordered(simplification_df$keep, levels = simplification_df$keep)
input_simplified = purrr::map_dfr(simplification_levels, .id = "id", function(x) {
  rmapshaper::ms_simplify(input_projected, keep_shapes = TRUE, keep = x)
})
input_simplified = left_join(
  input_simplified,
  simplification_df,
  by = join_by(id == id)
  )
tm_shape(input_simplified, bbox = tmaptools::bb(input_simplified, 1.1)) +
  tm_lines() +
  tm_facets(by = "keep", free.coords = TRUE) 
```

![](https://i.imgur.com/PUG4Bde.png)

<sup>Created on 2023-10-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by Robinlovelace** [comment]
My guess: you are running out-of-date versions of R or R packages.

**Comment by Robinlovelace** [comment]
What is your `sessionInfo()`?

Mine is

```
sessionInfo()
R version 4.3.1 (2023-06-16)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.3 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/London
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rmapshaper_0.5.0
```

**Comment by anisotropi4** [comment]
I'm going to set up a small R build GitHub, as I'm really struggling with library and version dependencies. I'll share `sessionInfo()` data once the rebuild is complete, and let you know what I've got

**Comment by anisotropi4** [comment]
I have created a small repository [here](https://github.com/anisotropi4/nutcracker) that builds a local `R` environment from source with the following `sessionInfo()`

    R version 4.3.1 (2023-06-16)
    Platform: x86_64-pc-linux-gnu (64-bit)
    Running under: Linux Mint 21.1

    Matrix products: default
    BLAS:   /home/user/nutcracker/lib/R/lib/libRblas.so 
    LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/liblapack.so.3;  LAPACK version 3.10.0

    locale:
     [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
     [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
     [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
     [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
     [9] LC_ADDRESS=C               LC_TELEPHONE=C
     [11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

    time zone: Europe/London
    tzcode source: system (glibc)

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base

    loaded via a namespace (and not attached):
    [1] compiler_4.3.1

It then installs the following libraries:

    install.packages("igraph")
    install.packages("qgisprocess")
    install.packages("reticulate")
    install.packages("rmarkdown")
    install.packages("rmapshaper")
    install.packages("sf")
    install.packages("stplanr")
    install.packages("stplanr") 
    install.packages("tidyverse")
    install.packages("tmap")

If I then run `quarto render paper.qmd` I get the following error:

    $ quarto render paper.qmd


    processing file: paper.qmd
    1/20                   
    2/20 [unnamed-chunk-1] 
    3/20                   
    4/20 [unnamed-chunk-2] 
    5/20                   
    6/20 [unnamed-chunk-3] 

    Quitting from lines 163-191 [unnamed-chunk-3] (paper.qmd)
    Error in `map()`:
    ℹ In index: 1.
    Caused by error:
    ! SyntaxError: Unexpected token '.'
    Backtrace:
      1. purrr::map_dfr(...)
     17. base::stop(`<std::nv_>`)
    Execution halted

Which is what I think was the error from before

**Comment by Robinlovelace** [comment]
Yes, that seems like a reproducible error, sorry about this! Will have a think, there must be a more robust way of doing this.
