### ISSUE TITLE
Tables for rasterio and shapely do not render

### ISSUE THREAD

**Issue by JosiahParry** [nptscot/networkmerge#76]
The outputs of these tables are shown as plain markdown and not rendered tables as desired. 

https://github.com/nptscot/networkmerge/blob/f3a4663b593dcc2a6ef0290500528530849c9e84/paper.qmd#L490

<img width="319" alt="image" src="https://github.com/nptscot/networkmerge/assets/13534508/87cec65a-a83f-4c6b-8f74-f04d56903510">

**Comment by Robinlovelace** [comment]
True that, noticed it... One that could be a quick fix with the recent `great_tables` Python package? Or could be a simpler fix, correct output but it sees it as plain text not markdown..

**Comment by JosiahParry** [comment]
Does output="asis" work with Python chunks?

**Comment by anisotropi4** [comment]
My bad. As it's markdown I don't know why it isn't rendering. Equally we could just cut this.

**Comment by Robinlovelace** [comment]
> My bad. As it's markdown I don't know why it isn't rendering. Equally we could just cut this.

No worries, go fast break things is a good approach at this stage.

Let's try be ambitious, sure we can fix this!
