### ISSUE TITLE
Knotted and unknotted figures the same

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#85]
Before knot removal:

![image](https://github.com/nptscot/networkmerge/assets/1825120/2df0d888-1efc-42e5-99a3-e479d3e94a59)

https://nptscot.github.io/networkmerge/paper.html#fig-skeleton-line

After knot removal:

![image](https://github.com/nptscot/networkmerge/assets/1825120/2343d534-388c-4caf-83af-48a48b1f92c5)

Source: https://nptscot.github.io/networkmerge/paper.html#fig-knots

I think there are 2 options here:

- Remove the knotting images
- Change the parameters so that the roundabout-like features are removed

Thoughts @anisotropi4 ?

**Comment by anisotropi4** [comment]
I'm going to link to the` images/knot-output.png` and `images/noknot-output.png` images based on the zoomed in pictures from Edinburgh, if that's ok? Happy to remove it or add it as an implementation detail in the appendix.

**Comment by Robinlovelace** [comment]
Fine by me.

**Comment by Robinlovelace** [comment]
I think it's an important detail so deserves being in the main body. Isn't it a method that applies equality to the voronoi and skeletonize approaches?

**Comment by anisotropi4** [comment]
As it is not an issue with the Voronoi simplification it is kind of in the right place but you have given me an idea though about what to do with the Voronoi code.

**Comment by anisotropi4** [comment]
Scrub that. There are knot features in the Voronoi network, so it does apply to both approaches. If you're ok with the update, I'd close this?

**Comment by Robinlovelace** [comment]
:+1: it's done and looking good:

![image](https://github.com/nptscot/networkmerge/assets/1825120/49e82c4a-356c-48c9-b552-073992746ecc)

In the results section can we show results in which those  features are removed? For sure I guess.
