### ISSUE TITLE
Layout of primal networks incorrect

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#86]
Any ideas how to fix this @wangzhao0217 and @anisotropi4? 

![image](https://github.com/nptscot/networkmerge/assets/1825120/363a40e3-1231-4b52-a94c-1c8349b7080e)

See issue rendered here: https://nptscot.github.io/networkmerge/paper.html#fig-knots

Source code: 

https://github.com/nptscot/networkmerge/blob/a37df483a922345e06f165fa0329dfc1e4472ac7/paper.qmd#L924-L934

**Comment by JosiahParry** [comment]
You may be able to fix this by combining the two statements into one chunk prefixed with

```
#| layout-ncol: 2
```

or however those comments are formatted

**Comment by Robinlovelace** [comment]
Will give it a go, thanks Josiah..
