### ISSUE TITLE
Package functions

### ISSUE THREAD

**Issue by Robinlovelace** [nptscot/networkmerge#97]
In conversation with Zhao, I'm imagining reading the paper for the first time and wanting to test it on my own data. How to do that? It's not clear from the paper. At present I think you need to either clone the [`arctic-tern`](https://github.com/anisotropi4/arctic-tern/tree/main) repo and put the inputs into the right place before running 

```bash
(venv) $ ./skeletonize.py data/your_data.geojson
```

Or run the code in `paper.qmd` line-by-line.

Thoughts @anisotropi4 and @JosiahParry, should we package this up and publish on [PyPI](https://pypi.org/)?

**Comment by Robinlovelace** [comment]
Zhao happy to take a look and help with the packaging side, if we go that direction, seems like a worthwhile endeavour to me if not too much time, enabling this to work (or similar):

```
pip install networkmerge
python
import networkmerge as ntm
rnet_simple = ntm.skeletonize(rnet)
```

**Comment by anisotropi4** [comment]
I complete agree. I would be happy for Zhao to take this on. Equally I'd be more than happy to help. If nothing else, I have some helper scripts will scrape the `Quarto` files to create `jupyter` and `python` scripts.
